//
// Created by AIDAN PRATT on 2/23/2024.
//

#ifndef KITTY_IDT_H
#define KITTY_IDT_H

#include <stdint.h>

// The IDT register (IDTR) is a pointer to the IDT descriptor. The IDT descriptor is a pointer to and size of the IDT.

/*
 * Initializes the IDT, creating 256 interrupt vectors and enables interrupts. Should only be included on x86_64.
 */

void init_idt();

/*
 * The descriptor structure for an interrupt gate, used in the IDT. Intel Manual Volume 3 Chapter 6.11
 */
struct interrupt_gate_descriptor {
    uint16_t offset_bits_0_15;
    uint16_t selector;
    uint8_t ist_offset;
    uint8_t type_dpl_present; // Type: Interrupt/Trap/Task, DPL: Privilege Level (Hardware Int Ignores), Present Bit: 1 for active.
    uint16_t offset_bits_16_31;
    uint32_t offset_bits_32_63;
    uint32_t zeroes;
}__attribute__((packed));

typedef struct interrupt_gate_descriptor interrupt_gate_descriptor;

/*
 * IDT is of a fixed length with 256 entries. sowwy :3;
 */
static struct {
    interrupt_gate_descriptor entry_0;
    interrupt_gate_descriptor entry_1;
    interrupt_gate_descriptor entry_2;
    interrupt_gate_descriptor entry_3;
    interrupt_gate_descriptor entry_4;
    interrupt_gate_descriptor entry_5;
    interrupt_gate_descriptor entry_6;
    interrupt_gate_descriptor entry_7;
    interrupt_gate_descriptor entry_8;
    interrupt_gate_descriptor entry_9;
    interrupt_gate_descriptor entry_10;
    interrupt_gate_descriptor entry_11;
    interrupt_gate_descriptor entry_12;
    interrupt_gate_descriptor entry_13;
    interrupt_gate_descriptor entry_14;
    interrupt_gate_descriptor entry_15;
    interrupt_gate_descriptor entry_16;
    interrupt_gate_descriptor entry_17;
    interrupt_gate_descriptor entry_18;
    interrupt_gate_descriptor entry_19;
    interrupt_gate_descriptor entry_20;
    interrupt_gate_descriptor entry_21;
    interrupt_gate_descriptor entry_22;
    interrupt_gate_descriptor entry_23;
    interrupt_gate_descriptor entry_24;
    interrupt_gate_descriptor entry_25;
    interrupt_gate_descriptor entry_26;
    interrupt_gate_descriptor entry_27;
    interrupt_gate_descriptor entry_28;
    interrupt_gate_descriptor entry_29;
    interrupt_gate_descriptor entry_30;
    interrupt_gate_descriptor entry_31;
    interrupt_gate_descriptor entry_32;
    interrupt_gate_descriptor entry_33;
    interrupt_gate_descriptor entry_34;
    interrupt_gate_descriptor entry_35;
    interrupt_gate_descriptor entry_36;
    interrupt_gate_descriptor entry_37;
    interrupt_gate_descriptor entry_38;
    interrupt_gate_descriptor entry_39;
    interrupt_gate_descriptor entry_40;
    interrupt_gate_descriptor entry_41;
    interrupt_gate_descriptor entry_42;
    interrupt_gate_descriptor entry_43;
    interrupt_gate_descriptor entry_44;
    interrupt_gate_descriptor entry_45;
    interrupt_gate_descriptor entry_46;
    interrupt_gate_descriptor entry_47;
    interrupt_gate_descriptor entry_48;
    interrupt_gate_descriptor entry_49;
    interrupt_gate_descriptor entry_50;
    interrupt_gate_descriptor entry_51;
    interrupt_gate_descriptor entry_52;
    interrupt_gate_descriptor entry_53;
    interrupt_gate_descriptor entry_54;
    interrupt_gate_descriptor entry_55;
    interrupt_gate_descriptor entry_56;
    interrupt_gate_descriptor entry_57;
    interrupt_gate_descriptor entry_58;
    interrupt_gate_descriptor entry_59;
    interrupt_gate_descriptor entry_60;
    interrupt_gate_descriptor entry_61;
    interrupt_gate_descriptor entry_62;
    interrupt_gate_descriptor entry_63;
    interrupt_gate_descriptor entry_64;
    interrupt_gate_descriptor entry_65;
    interrupt_gate_descriptor entry_66;
    interrupt_gate_descriptor entry_67;
    interrupt_gate_descriptor entry_68;
    interrupt_gate_descriptor entry_69;
    interrupt_gate_descriptor entry_70;
    interrupt_gate_descriptor entry_71;
    interrupt_gate_descriptor entry_72;
    interrupt_gate_descriptor entry_73;
    interrupt_gate_descriptor entry_74;
    interrupt_gate_descriptor entry_75;
    interrupt_gate_descriptor entry_76;
    interrupt_gate_descriptor entry_77;
    interrupt_gate_descriptor entry_78;
    interrupt_gate_descriptor entry_79;
    interrupt_gate_descriptor entry_80;
    interrupt_gate_descriptor entry_81;
    interrupt_gate_descriptor entry_82;
    interrupt_gate_descriptor entry_83;
    interrupt_gate_descriptor entry_84;
    interrupt_gate_descriptor entry_85;
    interrupt_gate_descriptor entry_86;
    interrupt_gate_descriptor entry_87;
    interrupt_gate_descriptor entry_88;
    interrupt_gate_descriptor entry_89;
    interrupt_gate_descriptor entry_90;
    interrupt_gate_descriptor entry_91;
    interrupt_gate_descriptor entry_92;
    interrupt_gate_descriptor entry_93;
    interrupt_gate_descriptor entry_94;
    interrupt_gate_descriptor entry_95;
    interrupt_gate_descriptor entry_96;
    interrupt_gate_descriptor entry_97;
    interrupt_gate_descriptor entry_98;
    interrupt_gate_descriptor entry_99;
    interrupt_gate_descriptor entry_100;
    interrupt_gate_descriptor entry_101;
    interrupt_gate_descriptor entry_102;
    interrupt_gate_descriptor entry_103;
    interrupt_gate_descriptor entry_104;
    interrupt_gate_descriptor entry_105;
    interrupt_gate_descriptor entry_106;
    interrupt_gate_descriptor entry_107;
    interrupt_gate_descriptor entry_108;
    interrupt_gate_descriptor entry_109;
    interrupt_gate_descriptor entry_110;
    interrupt_gate_descriptor entry_111;
    interrupt_gate_descriptor entry_112;
    interrupt_gate_descriptor entry_113;
    interrupt_gate_descriptor entry_114;
    interrupt_gate_descriptor entry_115;
    interrupt_gate_descriptor entry_116;
    interrupt_gate_descriptor entry_117;
    interrupt_gate_descriptor entry_118;
    interrupt_gate_descriptor entry_119;
    interrupt_gate_descriptor entry_120;
    interrupt_gate_descriptor entry_121;
    interrupt_gate_descriptor entry_122;
    interrupt_gate_descriptor entry_123;
    interrupt_gate_descriptor entry_124;
    interrupt_gate_descriptor entry_125;
    interrupt_gate_descriptor entry_126;
    interrupt_gate_descriptor entry_127;
    interrupt_gate_descriptor entry_128;
    interrupt_gate_descriptor entry_129;
    interrupt_gate_descriptor entry_130;
    interrupt_gate_descriptor entry_131;
    interrupt_gate_descriptor entry_132;
    interrupt_gate_descriptor entry_133;
    interrupt_gate_descriptor entry_134;
    interrupt_gate_descriptor entry_135;
    interrupt_gate_descriptor entry_136;
    interrupt_gate_descriptor entry_137;
    interrupt_gate_descriptor entry_138;
    interrupt_gate_descriptor entry_139;
    interrupt_gate_descriptor entry_140;
    interrupt_gate_descriptor entry_141;
    interrupt_gate_descriptor entry_142;
    interrupt_gate_descriptor entry_143;
    interrupt_gate_descriptor entry_144;
    interrupt_gate_descriptor entry_145;
    interrupt_gate_descriptor entry_146;
    interrupt_gate_descriptor entry_147;
    interrupt_gate_descriptor entry_148;
    interrupt_gate_descriptor entry_149;
    interrupt_gate_descriptor entry_150;
    interrupt_gate_descriptor entry_151;
    interrupt_gate_descriptor entry_152;
    interrupt_gate_descriptor entry_153;
    interrupt_gate_descriptor entry_154;
    interrupt_gate_descriptor entry_155;
    interrupt_gate_descriptor entry_156;
    interrupt_gate_descriptor entry_157;
    interrupt_gate_descriptor entry_158;
    interrupt_gate_descriptor entry_159;
    interrupt_gate_descriptor entry_160;
    interrupt_gate_descriptor entry_161;
    interrupt_gate_descriptor entry_162;
    interrupt_gate_descriptor entry_163;
    interrupt_gate_descriptor entry_164;
    interrupt_gate_descriptor entry_165;
    interrupt_gate_descriptor entry_166;
    interrupt_gate_descriptor entry_167;
    interrupt_gate_descriptor entry_168;
    interrupt_gate_descriptor entry_169;
    interrupt_gate_descriptor entry_170;
    interrupt_gate_descriptor entry_171;
    interrupt_gate_descriptor entry_172;
    interrupt_gate_descriptor entry_173;
    interrupt_gate_descriptor entry_174;
    interrupt_gate_descriptor entry_175;
    interrupt_gate_descriptor entry_176;
    interrupt_gate_descriptor entry_177;
    interrupt_gate_descriptor entry_178;
    interrupt_gate_descriptor entry_179;
    interrupt_gate_descriptor entry_180;
    interrupt_gate_descriptor entry_181;
    interrupt_gate_descriptor entry_182;
    interrupt_gate_descriptor entry_183;
    interrupt_gate_descriptor entry_184;
    interrupt_gate_descriptor entry_185;
    interrupt_gate_descriptor entry_186;
    interrupt_gate_descriptor entry_187;
    interrupt_gate_descriptor entry_188;
    interrupt_gate_descriptor entry_189;
    interrupt_gate_descriptor entry_190;
    interrupt_gate_descriptor entry_191;
    interrupt_gate_descriptor entry_192;
    interrupt_gate_descriptor entry_193;
    interrupt_gate_descriptor entry_194;
    interrupt_gate_descriptor entry_195;
    interrupt_gate_descriptor entry_196;
    interrupt_gate_descriptor entry_197;
    interrupt_gate_descriptor entry_198;
    interrupt_gate_descriptor entry_199;
    interrupt_gate_descriptor entry_200;
    interrupt_gate_descriptor entry_201;
    interrupt_gate_descriptor entry_202;
    interrupt_gate_descriptor entry_203;
    interrupt_gate_descriptor entry_204;
    interrupt_gate_descriptor entry_205;
    interrupt_gate_descriptor entry_206;
    interrupt_gate_descriptor entry_207;
    interrupt_gate_descriptor entry_208;
    interrupt_gate_descriptor entry_209;
    interrupt_gate_descriptor entry_210;
    interrupt_gate_descriptor entry_211;
    interrupt_gate_descriptor entry_212;
    interrupt_gate_descriptor entry_213;
    interrupt_gate_descriptor entry_214;
    interrupt_gate_descriptor entry_215;
    interrupt_gate_descriptor entry_216;
    interrupt_gate_descriptor entry_217;
    interrupt_gate_descriptor entry_218;
    interrupt_gate_descriptor entry_219;
    interrupt_gate_descriptor entry_220;
    interrupt_gate_descriptor entry_221;
    interrupt_gate_descriptor entry_222;
    interrupt_gate_descriptor entry_223;
    interrupt_gate_descriptor entry_224;
    interrupt_gate_descriptor entry_225;
    interrupt_gate_descriptor entry_226;
    interrupt_gate_descriptor entry_227;
    interrupt_gate_descriptor entry_228;
    interrupt_gate_descriptor entry_229;
    interrupt_gate_descriptor entry_230;
    interrupt_gate_descriptor entry_231;
    interrupt_gate_descriptor entry_232;
    interrupt_gate_descriptor entry_233;
    interrupt_gate_descriptor entry_234;
    interrupt_gate_descriptor entry_235;
    interrupt_gate_descriptor entry_236;
    interrupt_gate_descriptor entry_237;
    interrupt_gate_descriptor entry_238;
    interrupt_gate_descriptor entry_239;
    interrupt_gate_descriptor entry_240;
    interrupt_gate_descriptor entry_241;
    interrupt_gate_descriptor entry_242;
    interrupt_gate_descriptor entry_243;
    interrupt_gate_descriptor entry_244;
    interrupt_gate_descriptor entry_245;
    interrupt_gate_descriptor entry_246;
    interrupt_gate_descriptor entry_247;
    interrupt_gate_descriptor entry_248;
    interrupt_gate_descriptor entry_249;
    interrupt_gate_descriptor entry_250;
    interrupt_gate_descriptor entry_251;
    interrupt_gate_descriptor entry_252;
    interrupt_gate_descriptor entry_253;
    interrupt_gate_descriptor entry_254;
    interrupt_gate_descriptor entry_255;
}__attribute((aligned(0x10))) __attribute__((packed)) idt; // if you complain about the IDT code, you will be banned from contributing to the kitty kernel project.

static struct {
    uint16_t size; // One less than the size (max entry number, entries start at 0)
    uint64_t offset; // address of the IDT
}__attribute__((packed)) idt_descriptor;

/*
 * The Interrupt Service Routines (ISRs) defined in the interrupts.asm file.
 * Each corresponds to the Interrupt Descriptor Table (IDT) entry in idt.c
 */
extern void isr_0();
extern void isr_1();
extern void isr_2();
extern void isr_3();
extern void isr_4();
extern void isr_5();
extern void isr_6();
extern void isr_7();
extern void isr_8();
extern void isr_9();
extern void isr_10();
extern void isr_11();
extern void isr_12();
extern void isr_13();
extern void isr_14();
extern void isr_15();
extern void isr_16();
extern void isr_17();
extern void isr_18();
extern void isr_19();
extern void isr_20();
extern void isr_21();
extern void isr_22();
extern void isr_23();
extern void isr_24();
extern void isr_25();
extern void isr_26();
extern void isr_27();
extern void isr_28();
extern void isr_29();
extern void isr_30();
extern void isr_31();
extern void isr_32();
extern void isr_33();
extern void isr_34();
extern void isr_35();
extern void isr_36();
extern void isr_37();
extern void isr_38();
extern void isr_39();
extern void isr_40();
extern void isr_41();
extern void isr_42();
extern void isr_43();
extern void isr_44();
extern void isr_45();
extern void isr_46();
extern void isr_47();
extern void isr_48();
extern void isr_49();
extern void isr_50();
extern void isr_51();
extern void isr_52();
extern void isr_53();
extern void isr_54();
extern void isr_55();
extern void isr_56();
extern void isr_57();
extern void isr_58();
extern void isr_59();
extern void isr_60();
extern void isr_61();
extern void isr_62();
extern void isr_63();
extern void isr_64();
extern void isr_65();
extern void isr_66();
extern void isr_67();
extern void isr_68();
extern void isr_69();
extern void isr_70();
extern void isr_71();
extern void isr_72();
extern void isr_73();
extern void isr_74();
extern void isr_75();
extern void isr_76();
extern void isr_77();
extern void isr_78();
extern void isr_79();
extern void isr_80();
extern void isr_81();
extern void isr_82();
extern void isr_83();
extern void isr_84();
extern void isr_85();
extern void isr_86();
extern void isr_87();
extern void isr_88();
extern void isr_89();
extern void isr_90();
extern void isr_91();
extern void isr_92();
extern void isr_93();
extern void isr_94();
extern void isr_95();
extern void isr_96();
extern void isr_97();
extern void isr_98();
extern void isr_99();
extern void isr_100();
extern void isr_101();
extern void isr_102();
extern void isr_103();
extern void isr_104();
extern void isr_105();
extern void isr_106();
extern void isr_107();
extern void isr_108();
extern void isr_109();
extern void isr_110();
extern void isr_111();
extern void isr_112();
extern void isr_113();
extern void isr_114();
extern void isr_115();
extern void isr_116();
extern void isr_117();
extern void isr_118();
extern void isr_119();
extern void isr_120();
extern void isr_121();
extern void isr_122();
extern void isr_123();
extern void isr_124();
extern void isr_125();
extern void isr_126();
extern void isr_127();
extern void isr_128();
extern void isr_129();
extern void isr_130();
extern void isr_131();
extern void isr_132();
extern void isr_133();
extern void isr_134();
extern void isr_135();
extern void isr_136();
extern void isr_137();
extern void isr_138();
extern void isr_139();
extern void isr_140();
extern void isr_141();
extern void isr_142();
extern void isr_143();
extern void isr_144();
extern void isr_145();
extern void isr_146();
extern void isr_147();
extern void isr_148();
extern void isr_149();
extern void isr_150();
extern void isr_151();
extern void isr_152();
extern void isr_153();
extern void isr_154();
extern void isr_155();
extern void isr_156();
extern void isr_157();
extern void isr_158();
extern void isr_159();
extern void isr_160();
extern void isr_161();
extern void isr_162();
extern void isr_163();
extern void isr_164();
extern void isr_165();
extern void isr_166();
extern void isr_167();
extern void isr_168();
extern void isr_169();
extern void isr_170();
extern void isr_171();
extern void isr_172();
extern void isr_173();
extern void isr_174();
extern void isr_175();
extern void isr_176();
extern void isr_177();
extern void isr_178();
extern void isr_179();
extern void isr_180();
extern void isr_181();
extern void isr_182();
extern void isr_183();
extern void isr_184();
extern void isr_185();
extern void isr_186();
extern void isr_187();
extern void isr_188();
extern void isr_189();
extern void isr_190();
extern void isr_191();
extern void isr_192();
extern void isr_193();
extern void isr_194();
extern void isr_195();
extern void isr_196();
extern void isr_197();
extern void isr_198();
extern void isr_199();
extern void isr_200();
extern void isr_201();
extern void isr_202();
extern void isr_203();
extern void isr_204();
extern void isr_205();
extern void isr_206();
extern void isr_207();
extern void isr_208();
extern void isr_209();
extern void isr_210();
extern void isr_211();
extern void isr_212();
extern void isr_213();
extern void isr_214();
extern void isr_215();
extern void isr_216();
extern void isr_217();
extern void isr_218();
extern void isr_219();
extern void isr_220();
extern void isr_221();
extern void isr_222();
extern void isr_223();
extern void isr_224();
extern void isr_225();
extern void isr_226();
extern void isr_227();
extern void isr_228();
extern void isr_229();
extern void isr_230();
extern void isr_231();
extern void isr_232();
extern void isr_233();
extern void isr_234();
extern void isr_235();
extern void isr_236();
extern void isr_237();
extern void isr_238();
extern void isr_239();
extern void isr_240();
extern void isr_241();
extern void isr_242();
extern void isr_243();
extern void isr_244();
extern void isr_245();
extern void isr_246();
extern void isr_247();
extern void isr_248();
extern void isr_249();
extern void isr_250();
extern void isr_251();
extern void isr_252();
extern void isr_253();
extern void isr_254();
extern void isr_255();

#endif //KITTY_IDT_H
